name: vangram
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  go_router: ^9.0.3
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.9
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.0
  mask_text_input_formatter: ^2.9.0
  flutter_secure_storage: ^4.2.1
  intl: ^0.18.1
  flutter_animate: ^4.5.0
  pinput: ^4.0.0
  image_picker: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.2
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - .env
  fonts:
    - family: Arizonia
      fonts:
        - asset: assets/fonts/Arizonia-Regular.ttf
